### ISSUE TITLE
Responsive menu pdf

### ISSUE THREAD

**Issue by ciearius** [CodingSyndicate/CampusCneipe#3]
I've read on SO and some other [blogs](https://blog.devgenius.io/how-to-display-a-pdf-using-an-iframe-and-make-it-responsive-d3c3fcd3a460): in order to make a PDF in an iframe size to fit you can add `#view=fitH` at the end of the `src` property of the iframe. 

Can't test if this works for us rn.

**Comment by ciearius** [comment]
This might be useful @GeneralMine

**Comment by GeneralMine** [comment]
@ciearius thanks for the tip. But it didn't work. The main problem is that safari doesn't allow zooming out

**Comment by GeneralMine** [comment]
Fix temporarily using google drive as embedded viewer.
For the future all products and prices will be part of the website fetched from the backend
